export const REASON_CODES = [
  "TARGET_ALREADY_MET",
  "ZERO_BALANCE",
  "UNSUPPORTED_ASSET_STATE",
  "MULTIPLIER_WINDOW",
  "INSUFFICIENT_POSITION",
  "RETAINED_FLOOR",
  "NO_JUPITER_ROUTE",
  "QUOTE_EXPIRED",
  "SLIPPAGE_LIMIT",
  "RPC_STALE",
  "QUOTE_SEARCH_EXHAUSTED",
  "ELIGIBLE",
  "SELECTED",
  "LOWER_RANKED",
  "PYTH_NOT_ENABLED",
  "PYTH_UNAVAILABLE",
  "PYTH_NOT_ENTITLED",
  "PYTH_FEED_MISSING",
  "PYTH_STALE",
  "PYTH_SESSION_INVALID",
  "PYTH_LOW_PUBLISHER_COUNT",
  "PYTH_CONFIDENCE_TOO_WIDE",
  "PYTH_UNIT_UNVERIFIED",
  "PYTH_DIVERGENCE",
  "PYTH_VALID",
] as const;

export type ReasonCode = (typeof REASON_CODES)[number];

export const REASON_COPY: Readonly<Record<ReasonCode, string>> = {
  TARGET_ALREADY_MET: "Your existing USDC already covers this request.",
  ZERO_BALANCE: "This supported position is not held in the wallet.",
  UNSUPPORTED_ASSET_STATE: "The live mint state could not be verified safely.",
  MULTIPLIER_WINDOW: "Trading is blocked inside the multiplier activation safety window.",
  INSUFFICIENT_POSITION: "This position cannot supply the missing USDC at the current quote.",
  RETAINED_FLOOR: "Selling enough would leave less exposure than your retained floor.",
  NO_JUPITER_ROUTE: "Jupiter did not return an executable quote for this position.",
  QUOTE_EXPIRED: "The quote expired and the decision must be refreshed.",
  SLIPPAGE_LIMIT: "The returned quote exceeds your maximum slippage.",
  RPC_STALE: "The portfolio snapshot is too old to evaluate safely.",
  QUOTE_SEARCH_EXHAUSTED: "A safe raw input could not be resolved within the quote-search limit.",
  ELIGIBLE: "This position passes the current preservation and execution rules.",
  SELECTED: "Selected by the deterministic portfolio rule.",
  LOWER_RANKED: "Eligible, but ranked behind the selected position.",
  PYTH_NOT_ENABLED: "Reference protection was not applied.",
  PYTH_UNAVAILABLE: "Pyth reference protection is temporarily unavailable.",
  PYTH_NOT_ENTITLED: "The configured Pyth account cannot access the required stock reference.",
  PYTH_FEED_MISSING: "The required Pyth stock reference feed is missing.",
  PYTH_STALE: "A required Pyth price is stale or carried forward.",
  PYTH_SESSION_INVALID: "The underlying stock reference is closed or has an unknown session.",
  PYTH_LOW_PUBLISHER_COUNT: "A required Pyth feed has too few contributing publishers.",
  PYTH_CONFIDENCE_TOO_WIDE: "A required Pyth confidence interval is too wide.",
  PYTH_UNIT_UNVERIFIED: "The executable xStock price could not be derived from multiplier-correct displayed units.",
  PYTH_DIVERGENCE: "The tokenized stock is outside the permitted reference-price gap.",
  PYTH_VALID: "Reference protection passed with fresh, session-valid Pyth data.",
};
